Fix vulnerabilities by new image
open-cluster-management/grc-ui-api pull request #152
Opened 2021-07-22 19:03 UTC by ChunxiAlexLuo

2021-07-22 19:54 UTC, ChunxiAlexLuo commented
https://quay.io/repository/open-cluster-management/grc-ui-api/manifest/sha256:3955e019ce0ee9948e90bea856ffed5f8cab6e5666bd95576a46e4d007e81ed2?tab=vulnerabilities

2021-07-22 19:57 UTC, dhaiducek commented on Dockerfile
> +RUN microdnf update
I think we need to add:
```
RUN ./install-npm.sh
```
https://github.com/open-cluster-management/common-nodejs-parent/blob/6b20341a3d71efdb5e541a2b2b2727a6dcfb71c7/Dockerfile#L11-L14

2021-07-22 19:58 UTC, dhaiducek commented on Dockerfile
> +RUN microdnf update
Oh, nevermind--we run `node` directly.

2021-07-22 20:00 UTC, dhaiducek commented on Dockerfile
> +RUN microdnf update
Sorry for the back-and-forth between...myself. 😆 

Do we need to update the builder image at the top of the file? If so, we'll need to install NPM.

2021-07-22 20:19 UTC, dhaiducek requested changes

2021-07-22 20:19 UTC, dhaiducek commented on Dockerfile
> +RUN microdnf install git -y
The `make` targets below this rely on NPM, so I think we'll need to add:
```
RUN ./install-npm.sh
```
https://github.com/open-cluster-management/common-nodejs-parent/blob/6b20341a3d71efdb5e541a2b2b2727a6dcfb71c7/Dockerfile#L11-L14

2021-07-22 20:59 UTC, dhaiducek approved these changes

2021-07-22 21:05 UTC, merged

2021-07-23 01:17 UTC, dhaiducek commented
/cherry-pick release-2.3